### PR TITLE
Add Discourse button to forum

### PR DESCRIPTION
**Pull request by rbeucher**

### CODE REVIEW

**Comment by aidanheerdegen** [comment]
Do you want to do this now, or wait until we have the snazzy domain name?

**Comment by aidanheerdegen** [comment]
Oh BTW you have the old trailing "About" tab. I've fixed it in https://github.com/ACCESS-Hive/website/pull/157 so I guess if that is merged you can rebase on `main`.

**Comment by rbeucher** [comment]
We can change the link when we get the domain name

**Comment by rbeucher** [comment]
I'm rebasing

**Comment by aidanheerdegen** [comment]
I can still see the old About tab. It was in `main`, so might have to rebase again now that my PR has been merged.

**Review by aidanheerdegen — CHANGES_REQUESTED** [review]
Old about tab still there. Need to try rebasing again.

**Review by aidanheerdegen — APPROVED** [review]

**Pull request merged**
